"use client";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { customerSchema } from "@/lib/validators";
import { z } from "zod";
import Toast from "@/components/Toast";

type FormData = z.input<typeof customerSchema>; type Customer = { id:number; type:string; firstName?:string; lastName?:string; companyName?:string; taxCode?:string; vatNumber?:string; phone?:string; email?:string; archived:boolean; addresses:any[]; _count?:{quotes:number} };
const defaults: FormData = { type:"PRIVATO", firstName:"", lastName:"", companyName:"", taxCode:"", vatNumber:"", recipientCode:"", pec:"", phone:"", email:"", notes:"", archived:false, allowDuplicate:false, addresses:[{type:"RESIDENZA",address:"",streetNumber:"",postalCode:"",city:"",province:"",isDefault:true},{type:"INSTALLAZIONE",address:"",streetNumber:"",postalCode:"",city:"",province:"",isDefault:true}] };
export default function CustomerManager({ openInitially=false }: { openInitially?:boolean }) {
  const [customers,setCustomers]=useState<Customer[]>([]); const [query,setQuery]=useState(""); const [modal,setModal]=useState(openInitially); const [editing,setEditing]=useState<Customer|null>(null); const [toast,setToast]=useState<{m:string;e?:boolean}|null>(null);
  const form=useForm<FormData>({resolver:zodResolver(customerSchema),defaultValues:defaults}); const type=form.watch("type");
  async function load(){const res=await fetch(`/api/customers?q=${encodeURIComponent(query)}`);setCustomers(await res.json());}
  useEffect(()=>{load()},[]); useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[query]);
  function open(customer?:Customer){setEditing(customer||null);form.reset((customer?{...customer,allowDuplicate:false,addresses:customer.addresses.length?customer.addresses:defaults.addresses}:defaults) as FormData);setModal(true)}
  function copyAddress(){const residence=form.getValues("addresses.0");form.setValue("addresses.1",{...residence,type:"INSTALLAZIONE",isDefault:true},{shouldDirty:true});}
  async function submit(data:FormData){const url=editing?`/api/customers/${editing.id}`:"/api/customers";let res=await fetch(url,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(res.status===409){if(confirm("È stato rilevato un possibile duplicato. Vuoi salvare comunque?")){res=await fetch(url,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,allowDuplicate:true})})}}const body=await res.json();if(!res.ok){setToast({m:body.error||"Salvataggio non riuscito",e:true});return}setModal(false);setToast({m:"Cliente salvato correttamente"});await load()}
  async function remove(customer:Customer){if(!confirm(`Eliminare o archiviare ${customer.companyName||`${customer.firstName||""} ${customer.lastName||""}`}?`))return;const res=await fetch(`/api/customers/${customer.id}`,{method:"DELETE"});const body=await res.json();setToast({m:body.message||"Operazione completata",e:!res.ok});load()}
  const title=useMemo(()=>editing?"Modifica cliente":"Nuovo cliente",[editing]);
  return <><div className="card"><div className="card-header"><div className="field" style={{minWidth:280}}><label htmlFor="customer-search">Cerca cliente</label><input id="customer-search" className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, telefono, e-mail o codice fiscale"/></div><button className="btn btn-primary" onClick={()=>open()}>+ Crea cliente</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Cliente</th><th>Contatti</th><th>Comune</th><th>CF / P.IVA</th><th>Preventivi</th><th>Azioni</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><div className="table-title">{c.companyName||`${c.firstName||""} ${c.lastName||""}`}</div><div className="table-sub">{c.type==="AZIENDA"?"Azienda":"Privato"}</div></td><td>{c.phone||"—"}<div className="table-sub">{c.email||""}</div></td><td>{c.addresses.find(a=>a.type==="INSTALLAZIONE")?.city||c.addresses[0]?.city||"—"}</td><td>{c.taxCode||c.vatNumber||"—"}</td><td>{c._count?.quotes||0}</td><td><div className="actions"><button className="btn btn-secondary btn-sm" onClick={()=>open(c)}>Modifica</button><button className="btn btn-danger btn-sm" onClick={()=>remove(c)}>Elimina</button></div></td></tr>)}</tbody></table>{!customers.length&&<div className="empty"><strong>Nessun cliente trovato</strong>Prova una ricerca diversa o crea una nuova anagrafica.</div>}</div></div>
  {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="modal" onSubmit={form.handleSubmit(submit)}><div className="modal-header"><h2>{title}</h2><button type="button" className="icon-btn" onClick={()=>setModal(false)}>×</button></div><div className="modal-body"><div className="form-grid">
    <div className="field"><label>Tipologia cliente</label><select className="select" {...form.register("type")}><option value="PRIVATO">Privato</option><option value="AZIENDA">Azienda</option></select></div><div/>
    {type==="PRIVATO"?<><div className="field"><label>Nome</label><input className="input" {...form.register("firstName")}/><span className="error-text">{form.formState.errors.firstName?.message}</span></div><div className="field"><label>Cognome</label><input className="input" {...form.register("lastName")}/></div></>:<div className="field span-2"><label>Ragione sociale</label><input className="input" {...form.register("companyName")}/><span className="error-text">{form.formState.errors.companyName?.message}</span></div>}
    <div className="field"><label>Codice fiscale</label><input className="input" {...form.register("taxCode")}/></div><div className="field"><label>Partita IVA</label><input className="input" {...form.register("vatNumber")}/></div>
    <div className="field"><label>Codice destinatario</label><input className="input" {...form.register("recipientCode")}/></div><div className="field"><label>PEC</label><input className="input" {...form.register("pec")}/></div>
    <div className="field"><label>Telefono</label><input className="input" {...form.register("phone")}/></div><div className="field"><label>E-mail</label><input type="email" className="input" {...form.register("email")}/><span className="error-text">{form.formState.errors.email?.message}</span></div>
    <div className="section-title">Residenza o sede</div>{[0,1].map((i)=><div className="span-full form-grid" key={i}>{i===1&&<div className="section-title" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span>Indirizzo di installazione</span><button type="button" className="btn btn-secondary btn-sm" onClick={copyAddress}>Copia dalla residenza</button></div>}<input type="hidden" {...form.register(`addresses.${i}.type` as const)}/><div className="field"><label>Indirizzo</label><input className="input" {...form.register(`addresses.${i}.address` as const)}/></div><div className="field"><label>Civico</label><input className="input" {...form.register(`addresses.${i}.streetNumber` as const)}/></div><div className="field"><label>CAP</label><input className="input" {...form.register(`addresses.${i}.postalCode` as const)}/></div><div className="field"><label>Comune</label><input className="input" {...form.register(`addresses.${i}.city` as const)}/></div><div className="field"><label>Provincia</label><input className="input" maxLength={2} {...form.register(`addresses.${i}.province` as const)}/></div></div>)}
    <div className="field span-full"><label>Note</label><textarea className="textarea" {...form.register("notes")}/></div></div></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={()=>setModal(false)}>Annulla</button><button className="btn btn-primary" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?"Salvataggio…":"Salva cliente"}</button></div></form></div>}
  {toast&&<Toast message={toast.m} error={toast.e} onClose={()=>setToast(null)}/>}</>;
}
