"use client";
import { useEffect,useState } from "react";
import { useForm } from "react-hook-form";
import Toast from "@/components/Toast";
import { formatCurrency } from "@/lib/format";
type Category={id:number;name:string}; type Attachment={id:number;originalName:string;sizeBytes:number}; type Product={id:number;internalCode:string;name:string;categoryId:number;category:Category;subcategory?:string;brand?:string;model?:string;description?:string;power?:string;capacity?:string;unit:string;salePriceInclVatCents:number;salePriceExclVatCents:number;vatRate:any;purchaseCostCents:number;supplier?:string;internalNotes?:string;quoteDescription?:string;technicalConfiguration?:string;imagePath?:string;active:boolean;attachments:Attachment[]};
type Form={internalCode:string;name:string;categoryId:string;subcategory:string;brand:string;model:string;description:string;power:string;capacity:string;unit:string;salePriceInclVat:string;salePriceExclVat:string;vatRate:string;purchaseCost:string;supplier:string;internalNotes:string;quoteDescription:string;technicalConfiguration:string;active:boolean};
const defaults:Form={internalCode:"",name:"",categoryId:"",subcategory:"",brand:"",model:"",description:"",power:"",capacity:"",unit:"pz",salePriceInclVat:"0,00",salePriceExclVat:"0,00",vatRate:"22",purchaseCost:"0,00",supplier:"",internalNotes:"",quoteDescription:"",technicalConfiguration:"",active:true};
const euros=(v:string)=>Math.round((Number(v.replace(".","").replace(",","."))||0)*100); const euroInput=(c:number)=> (c/100).toFixed(2).replace(".",",");
export default function ProductManager({openInitially=false}:{openInitially?:boolean}){const[products,setProducts]=useState<Product[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[q,setQ]=useState("");const[modal,setModal]=useState(openInitially);const[editing,setEditing]=useState<Product|null>(null);const[imageFile,setImageFile]=useState<File|null>(null);const[imagePreview,setImagePreview]=useState<string|null>(null);const[removeCurrentImage,setRemoveCurrentImage]=useState(false);const[toast,setToast]=useState<{m:string;e?:boolean}|null>(null);const form=useForm<Form>({defaultValues:defaults});
  async function load(){const[a,b]=await Promise.all([fetch(`/api/products?q=${encodeURIComponent(q)}`),fetch("/api/categories")]);setProducts(await a.json());setCategories(await b.json())} useEffect(()=>{load()},[]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q]);
  function open(p?:Product){setEditing(p||null);setImageFile(null);setImagePreview(null);setRemoveCurrentImage(false);setToast(null);form.reset(p?{...defaults,...p,categoryId:String(p.categoryId),salePriceInclVat:euroInput(p.salePriceInclVatCents),salePriceExclVat:euroInput(p.salePriceExclVatCents),purchaseCost:euroInput(p.purchaseCostCents),vatRate:String(p.vatRate)}:defaults);setModal(true)}
  async function submit(v:Form){const current=editing;const body={...v,categoryId:Number(v.categoryId),salePriceInclVatCents:euros(v.salePriceInclVat),salePriceExclVatCents:euros(v.salePriceExclVat),purchaseCostCents:euros(v.purchaseCost),vatRate:Number(v.vatRate)};const res=await fetch(current?`/api/products/${current.id}`:"/api/products",{method:current?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});let data=await res.json();if(!res.ok){setToast({m:data.error||"Errore",e:true});return}setEditing(data);if(imageFile){const fd=new FormData();fd.set("file",imageFile);const imageRes=await fetch(`/api/products/${data.id}/image`,{method:"POST",body:fd});const imageData=await imageRes.json();if(!imageRes.ok){setToast({m:`Prodotto salvato, ma la foto non è stata caricata: ${imageData.error||"errore"}`,e:true});return}data=imageData}else if(removeCurrentImage&&current?.imagePath){const imageRes=await fetch(`/api/products/${data.id}/image`,{method:"DELETE"});if(!imageRes.ok){setToast({m:"Prodotto salvato, ma la foto non è stata eliminata",e:true});return}data={...data,imagePath:null}}setEditing(data);setImageFile(null);setImagePreview(null);setRemoveCurrentImage(false);setToast({m:"Prodotto salvato"});setModal(false);load()}
  async function remove(p:Product){if(!confirm(`Eliminare o disattivare ${p.name}?`))return;const res=await fetch(`/api/products/${p.id}`,{method:"DELETE"});setToast({m:res.ok?"Operazione completata":"Eliminazione non riuscita",e:!res.ok});load()}
  async function upload(file:File){if(!editing)return;const fd=new FormData();fd.set("file",file);const res=await fetch(`/api/products/${editing.id}/attachments`,{method:"POST",body:fd});const data=await res.json();if(!res.ok){setToast({m:data.error,e:true});return}setEditing({...editing,attachments:[...editing.attachments,data]});setToast({m:"Scheda tecnica caricata"});load()}
  function chooseImage(file?:File){if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setToast({m:"Sono accettate immagini JPG, PNG o WebP",e:true});return}if(file.size>10*1024*1024){setToast({m:"L’immagine supera 10 MB",e:true});return}setImageFile(file);setRemoveCurrentImage(false);const reader=new FileReader();reader.onload=()=>setImagePreview(String(reader.result));reader.readAsDataURL(file)}
  function clearImage(){setImageFile(null);setImagePreview(null);setRemoveCurrentImage(Boolean(editing?.imagePath))}
  async function deleteAttachment(id:number){if(!confirm("Eliminare la scheda tecnica?"))return;await fetch(`/api/attachments/${id}`,{method:"DELETE"});if(editing)setEditing({...editing,attachments:editing.attachments.filter(a=>a.id!==id)});load()}
  const imageSrc=imagePreview||(!removeCurrentImage&&editing?.imagePath?`/api/products/${editing.id}/image`:null);
  return <><div className="card"><div className="card-header"><div className="field" style={{minWidth:280}}><label htmlFor="product-search">Cerca nel catalogo</label><input id="product-search" className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, codice, marca o modello"/></div><button className="btn btn-primary" onClick={()=>open()}>+ Inserisci prodotto</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Codice</th><th>Foto</th><th>Prodotto</th><th>Categoria</th><th>Prezzo IVA incl.</th><th>Costo interno</th><th>Schede</th><th>Azioni</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.internalCode}</td><td>{p.imagePath&&<img src={`/api/products/${p.id}/image`} alt="" style={{width:58,height:46,objectFit:"contain",borderRadius:6}}/>}</td><td><div className="table-title">{p.name}</div><div className="table-sub">{[p.brand,p.model,p.power].filter(Boolean).join(" · ")}</div></td><td>{p.category.name}</td><td><strong>{formatCurrency(p.salePriceInclVatCents)}</strong></td><td>{formatCurrency(p.purchaseCostCents)}</td><td>{p.attachments.length}</td><td><div className="actions"><button className="btn btn-secondary btn-sm" onClick={()=>open(p)}>Modifica</button><button className="btn btn-danger btn-sm" onClick={()=>remove(p)}>Elimina</button></div></td></tr>)}</tbody></table>{!products.length&&<div className="empty"><strong>Nessun prodotto</strong>Inserisci il primo prodotto nel catalogo.</div>}</div></div>
  {modal&&<div className="modal-backdrop"><form className="modal" onSubmit={form.handleSubmit(submit)}><div className="modal-header"><h2>{editing?"Modifica prodotto":"Nuovo prodotto"}</h2><button type="button" className="icon-btn" onClick={()=>setModal(false)}>×</button></div><div className="modal-body"><div className="form-grid form-grid-3"><div className="field"><label>Codice interno *</label><input className="input" required {...form.register("internalCode")}/></div><div className="field span-2"><label>Nome commerciale *</label><input className="input" required {...form.register("name")}/></div><div className="field"><label>Categoria *</label><select className="select" required {...form.register("categoryId")}><option value="">Seleziona</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Sottocategoria</label><input className="input" {...form.register("subcategory")}/></div><div className="field"><label>Unità di misura</label><input className="input" {...form.register("unit")}/></div><div className="field"><label>Marca</label><input className="input" {...form.register("brand")}/></div><div className="field"><label>Modello</label><input className="input" {...form.register("model")}/></div><div className="field"><label>Potenza</label><input className="input" {...form.register("power")}/></div><div className="field"><label>Capacità</label><input className="input" {...form.register("capacity")}/></div><div className="field"><label>Prezzo IVA inclusa (€)</label><input className="input" inputMode="decimal" {...form.register("salePriceInclVat")}/></div><div className="field"><label>Prezzo IVA esclusa (€)</label><input className="input" inputMode="decimal" {...form.register("salePriceExclVat")}/></div><div className="field"><label>Aliquota IVA (%)</label><input className="input" type="number" step="0.01" {...form.register("vatRate")}/></div><div className="field"><label>Costo acquisto interno (€)</label><input className="input" inputMode="decimal" {...form.register("purchaseCost")}/></div><div className="field span-2"><label>Fornitore</label><input className="input" {...form.register("supplier")}/></div><div className="field span-full"><label>Descrizione</label><textarea className="textarea" {...form.register("description")}/></div><div className="field span-full"><label>Descrizione predefinita per preventivo</label><textarea className="textarea" {...form.register("quoteDescription")}/></div><div className="field span-full"><label>Configurazione tecnica (note strutturate)</label><textarea className="textarea" {...form.register("technicalConfiguration")}/></div><div className="field span-full"><label>Note interne</label><textarea className="textarea" {...form.register("internalNotes")}/></div><label className="actions span-full"><input type="checkbox" {...form.register("active")}/> Prodotto attivo</label>
    <div className="span-full"><div className="section-title">Foto prodotto nel preventivo</div><div className="actions" style={{marginTop:12}}>{imageSrc&&<img src={imageSrc} alt={form.watch("name")||"Anteprima prodotto"} style={{width:150,height:110,objectFit:"contain",border:"1px solid var(--line)",borderRadius:8}}/>}<label className="btn btn-secondary">{imageSrc?"Sostituisci foto":"+ Carica foto"}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/></label>{imageSrc&&<button type="button" className="btn btn-danger btn-sm" onClick={clearImage}>Elimina foto</button>}<small>JPG, PNG o WebP, massimo 10 MB. La foto apparirà nel preventivo.</small></div></div>
    {editing&&<div className="span-full"><div className="section-title">Schede tecniche PDF</div><div className="actions" style={{marginTop:12}}><label className="btn btn-secondary">+ Carica PDF<input hidden type="file" accept="application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label>{editing.attachments.map(a=><span key={a.id} className="badge badge-emesso"><a href={`/api/attachments/${a.id}`} target="_blank">{a.originalName} ({(a.sizeBytes/1024).toFixed(0)} KB)</a><button type="button" onClick={()=>deleteAttachment(a.id)} style={{border:0,background:"none",color:"inherit"}}>×</button></span>)}</div></div>}
  </div></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={()=>setModal(false)}>Annulla</button><button className="btn btn-primary" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?"Salvataggio…":"Salva prodotto"}</button></div></form></div>}{toast&&<Toast message={toast.m} error={toast.e} onClose={()=>setToast(null)}/>}</>}
